# Generated by Django 4.0.2 on 2022-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='enddate',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='trip',
            name='startdate',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
