# Generated by Django 4.0.2 on 2022-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trip_enddate_alter_trip_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.PositiveBigIntegerField(),
        ),
    ]
