# Generated by Django 4.0.2 on 2022-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_flightforminput'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightforminput',
            name='adults',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightforminput',
            name='children',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightforminput',
            name='origin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightforminput',
            name='outbound_date',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightforminput',
            name='return_date',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
