# Generated by Django 4.0.2 on 2022-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_flightforminput_adults_flightforminput_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='adults',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='children',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='origin', max_length=100),
            preserve_default=False,
        ),
    ]
